name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: make executable
          run: chmod +x build.sh
        - name: build
          run: ./build.sh
    tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v4
        - name: make executable
          run: chmod +x build.sh
        - name: build
          run: ./build.sh
        - name: run tests
          working-directory: build
          run: ./tests
    cppcheck:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: install cppcheck
            run: sudo apt install cppcheck
          - name: run cppcheck
            run: cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem src/ tests/
    formatting-check: 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: install clang-format
            run: sudo apt install clang-format
          - name: run clang-format check
            run: find src/ tests/ \( -name "*.cpp" -o -name "*.h" \) | xargs clang-format --dry-run --Werror
